#!/usr/bin/env python3
"""Render .agents/local/DevelopmentMachine.md from machine-profile JSON + operator facts.

Reads machine-profile JSON on stdin (or --probe-json) and the operator facts
file (--facts), and writes a deterministic, secret-free .agents/local/DevelopmentMachine.md.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

FORBIDDEN_MARKERS = [
    "-----BEGIN",
    "ghp_",
    "gho_",
    "ghs_",
    "xox",
    "api_key=",
    "password=",
]
FORBIDDEN_PATTERNS = [
    re.compile(r"sk-[A-Za-z0-9]{24,}"),  # OpenAI-style key, avoids "task-" etc.
]


def load_json(text: str, where: str) -> dict:
    try:
        return json.loads(text)
    except json.JSONDecodeError as exc:
        raise SystemExit(f"ERROR: invalid JSON in {where}: {exc}") from exc


def load_facts(path: str) -> dict:
    p = Path(path)
    if not p.exists():
        return {}
    text = p.read_text(encoding="utf-8")
    m = re.search(r"```json\s*\n(.*?)\n```", text, re.DOTALL)
    if not m:
        raise SystemExit(f"ERROR: no ```json fence found in facts file {p}")
    return load_json(m.group(1), str(p))


def guard(payload: dict, where: str) -> None:
    s = json.dumps(payload)
    for marker in FORBIDDEN_MARKERS:
        if marker in s:
            raise SystemExit(
                f"ERROR: forbidden secret marker {marker!r} found in {where}; refusing to render"
            )
    for pattern in FORBIDDEN_PATTERNS:
        if pattern.search(s):
            raise SystemExit(
                f"ERROR: forbidden secret pattern {pattern.pattern!r} found in {where}; refusing to render"
            )


def md_table(headers: list[str], rows: list[list[str]]) -> list[str]:
    lines = ["| " + " | ".join(headers) + " |", "|" + "---|" * len(headers)]
    for row in rows:
        lines.append("| " + " | ".join(str(c).replace("|", "\\|") for c in row) + " |")
    return lines


def commands_from_help(text: str) -> list[str]:
    """Best-effort extraction of top-level command names from typer/rich or click help."""
    seen, out = set(), []
    for line in text.splitlines():
        m = re.match(r"^\s*│\s([a-z][a-z0-9-]*)", line) or re.match(r"^  ([a-z][a-z0-9-]*)\s", line)
        if m:
            c = m.group(1)
            if c in ("usage", "options", "commands"):
                continue
            if c not in seen:
                seen.add(c)
                out.append(c)
    return out


def code_block(text: str) -> list[str]:
    return ["```", text.rstrip("\n"), "```"]


def render(probe: dict, facts: dict) -> str:
    out: list[str] = []
    host = probe.get("host", {})
    runtime = probe.get("runtime", {})
    toolchain = probe.get("toolchain", [])
    backends = probe.get("agent_backends", {})
    ext = probe.get("external_services", {})
    doc = probe.get("documented_interfaces", {})
    cred = probe.get("credential_surface", {})
    facts_cred = facts.get("credential_surface", {})
    facts_services = facts.get("services", {})
    evidence = facts.get("evidence_status", [])
    facts_notes = facts.get("notes", "")

    # ---- header + scope ----
    out += [
        "# Development Machine",
        "",
        "> Secret-free profile of this development machine: versions, documented",
        "> wiring, and evidence status only — never credentials. Regenerate with:",
        ">",
        ">     bash .agents/skills/development-machine-profile/scripts/probe-host.sh \\",
        ">       | python3 .agents/skills/development-machine-profile/scripts/render-profile.py \\",
        ">           --facts .agents/knowledge/development-machine-facts.md",
        "",
        "## Scope",
        "",
        "- Covers this machine only; generated by the `development-machine-profile` skill.",
        "- Records facts that affect developing the product Agent: host resources,",
        "  toolchain, agent backends, the Harbor interface surface, and available",
        "  external services.",
        "- No credentials: environment-variable **names**, endpoints, and file paths",
        "  are metadata; secrets are supplied by the operator at run time via",
        "  `${VAR}` expansion and are never printed.",
        f"- Probe generated: {probe.get('generated_at', 'unknown')}",
        "",
    ]

    # ---- host identity ----
    out += ["## Host identity", ""]
    rows = [
        ("Hostname", host.get("hostname", "")),
        ("OS", host.get("os", "")),
        ("Kernel", host.get("kernel", "")),
        ("Architecture", host.get("arch", "")),
        ("CPU", host.get("cpu_model", "")),
        ("Cores", host.get("cpu_cores", "")),
        ("Memory (total)", host.get("ram_total", "")),
        ("GPU", host.get("gpu", "")),
    ]
    out += md_table(["Property", "Value"], rows)
    out += [""]

    # ---- storage ----
    out += ["## Storage", ""]
    storage = host.get("storage", [])
    if storage:
        out += md_table(
            ["Filesystem", "Size", "Avail", "Use%", "Mount"],
            [[s.get("filesystem", ""), s.get("size", ""), s.get("avail", ""), s.get("use%", ""), s.get("mount", "")]
             for s in storage],
        )
    else:
        out += ["_No storage data captured._"]
    out += [""]

    # ---- runtime ----
    out += ["## Runtime environment", ""]
    out += md_table(
        ["Property", "Value"],
        [
            ("Shell", runtime.get("shell", "")),
            ("Package managers", ", ".join(runtime.get("package_managers", []))),
        ],
    )
    runtimes = runtime.get("runtimes", {})
    for rt, ver in sorted(runtimes.items()):
        out.append(f"- `{rt}`: {ver or '_not present_'}")
    out += [""]

    # ---- toolchain ----
    out += ["## Toolchain versions", ""]
    if toolchain:
        out += md_table(
            ["Tool", "Path", "Version"],
            [[t.get("name", ""), t.get("path", ""), t.get("version", "")] for t in toolchain],
        )
    else:
        out += ["_No toolchain captured._"]
    out += [""]

    # ---- agent backends ----
    out += ["## Agent backends & task executors", ""]
    rows = []
    for name, b in backends.items():
        if name == "harbor":
            continue
        rows.append([name, b.get("version", ""), b.get("role", "")])
    out += md_table(["Backend", "Version", "Role"], rows)
    harbor = backends.get("harbor", {})
    out += [
        "",
        f"- `harbor` {harbor.get('version', '')} — {harbor.get('role', '')} (`{harbor.get('path', '')}`)",
        "",
    ]
    supported = harbor.get("supported_agents", "")
    if supported:
        out += ["### Supported agents (from `harbor run --help`, runtime observation)", ""]
        out += code_block(supported)
        out += [""]

    # ---- external services ----
    out += ["## External services", ""]
    out += md_table(
        ["Service", "Path", "Version", "Extra"],
        [
            ("lark-cli (Feishu/Lark)", ext.get("lark_cli", {}).get("path", ""), ext.get("lark_cli", {}).get("version", ""), ""),
            ("hf (Hugging Face)", ext.get("hf", {}).get("path", ""), ext.get("hf", {}).get("version", ""), ""),
            ("orca (Orca CLI)", ext.get("orca", {}).get("path", ""), ext.get("orca", {}).get("version", ""), ""),
            ("docker", ext.get("docker", {}).get("path", ""), ext.get("docker", {}).get("version", ""), f"daemon: {ext.get('docker', {}).get('daemon', '')}"),
        ],
    )
    out += [""]
    ssh_hosts = ext.get("ssh_hosts", [])
    surfaces = []
    for tool, label in (("hf", "hf"), ("docker", "docker")):
        cmds = commands_from_help(doc.get(tool, ""))
        if cmds:
            surfaces.append((label, cmds))
    if surfaces:
        out += ["### External CLI command surfaces", ""]
        for label, cmds in surfaces:
            out.append(f"- `{label}`: " + ", ".join(f"`{c}`" for c in cmds))
        out += [""]
    lark_help = doc.get("lark_cli", "")
    if lark_help:
        out += ["`lark-cli` quickstart (from `--help`):", ""]
        out += code_block(lark_help[:2000])
        out += [""]
    orca_help = doc.get("orca", "")
    if orca_help:
        out += ["`orca` command groups (from `--help`):", ""]
        out += code_block(orca_help[:1500])
        out += [""]
    if ssh_hosts:
        out += ["### SSH host aliases (names only; addresses omitted)", ""]
        out.append("- " + ", ".join(f"`{h}`" for h in ssh_hosts))
        out += [""]
    listening = ext.get("listening_services", [])
    if listening:
        out += ["### Local listening services (port + process name only)", ""]
        out += md_table(
            ["Address", "Port", "Process"],
            [[s.get("addr", ""), s.get("port", ""), s.get("proc", "")] for s in listening],
        )
        out += [""]
    cloud = ext.get("cloud_services", [])
    if cloud:
        out += ["### Cloud / external API services (reachability + env presence)", ""]
        out += md_table(
            ["Service", "Endpoint", "Auth env", "Env present", "HTTP status"],
            [[c.get("name", ""), c.get("endpoint", ""), c.get("env", ""), c.get("env_present", ""), c.get("http_status", "")]
             for c in cloud],
        )
        out += [""]
    if facts_services:
        out += ["### Documented external API services (secret-free)", ""]
        for name, s in sorted(facts_services.items()):
            out += [f"#### {name}", ""]
            rows = []
            if s.get("endpoint"):
                rows.append(("Endpoint", s["endpoint"]))
            if s.get("env_vars"):
                rows.append(("Env vars", ", ".join(f"`{v}`" for v in s["env_vars"])))
            if s.get("auth_header"):
                rows.append(("Auth header", f"`{s['auth_header']}`"))
            if s.get("documented_endpoints"):
                rows.append(("Endpoints", ", ".join(f"`{e}`" for e in s["documented_endpoints"])))
            if rows:
                out += md_table(["Field", "Value"], rows)
            if s.get("notes"):
                out += ["", s["notes"]]
            out += [""]

    # ---- harbor interface surface ----
    out += ["## Harbor interface surface", ""]
    top_cmds = commands_from_help(doc.get("harbor", ""))
    if top_cmds:
        out.append("Top-level commands: " + ", ".join(f"`{c}`" for c in top_cmds))
        out += [""]
    out += [
        "| Interface | Harbor mapping |",
        "|---|---|",
        "| workspace | `--jobs-dir` / `-o` (default `jobs`) |",
        "| task | `harbor task init/download/update/...` + `task.toml` / `dataset.toml` |",
        "| timeout | `--timeout-multiplier`, `--agent-timeout-multiplier`, `--verifier-timeout-multiplier`, `--agent-setup-timeout-multiplier`, `--environment-build-timeout-multiplier` |",
        "| result | `jobs/<job>/<trial>/` layout + reward + `verifier/test-stdout.txt` |",
        "| trajectory | `harbor analyze` / `harbor view` (per-trial trajectory files) |",
        "| auth | `harbor auth login` (GitHub OAuth) / `logout` / `status` / `key` / `org` |",
        "| adapter | `harbor adapter init` / `review` |",
        "| agent env | `--ak` / `--ae` with `${VAR}` template expansion; `--env-file`; `--allow-agent-host` |",
        "",
        "Full `harbor run --help` (runtime observation):",
        "",
    ]
    out += code_block(doc.get("harbor_run", ""))
    out += [""]

    # ---- provider wiring (secret-free) ----
    out += ["## Documented provider wiring (secret-free)", ""]
    if cred:
        out += ["### Environment variables present (names only — never values)", ""]
        out += md_table(
            ["Variable", "Present"],
            [[k, v] for k, v in sorted(cred.items())],
        )
        out += [""]
    if facts_cred:
        for family, f in sorted(facts_cred.items()):
            out += [f"### {family}", ""]
            rows = []
            if f.get("endpoint"):
                rows.append(("Endpoint", f["endpoint"]))
            if f.get("env_vars"):
                rows.append(("Env vars", ", ".join(f"`{v}`" for v in f["env_vars"])))
            if f.get("auth_files"):
                rows.append(("Auth files (metadata)", ", ".join(f"`{v}`" for v in f["auth_files"])))
            if f.get("discovery_commands"):
                rows.append(("Discovery", "; ".join(f"`{c}`" for c in f["discovery_commands"])))
            if rows:
                out += md_table(["Field", "Value"], rows)
            if f.get("notes"):
                out += [f"", f.get("notes", "")]
            out += [""]
    else:
        out += [
            "_TODO(operator): fill `.agents/knowledge/development-machine-facts.md` with",
            "credential_surface (endpoints, env-var names, auth-file paths, discovery",
            "commands) — metadata only, never secret values._",
            "",
        ]

    # ---- safe command shapes ----
    out += ["## Safe preflight & smoke command shapes", ""]
    out += ["Preflight (read-only, secret-free):", ""]
    out += code_block("bash .agents/skills/development-machine-profile/scripts/probe-host.sh")
    out += [""]
    if facts_cred:
        out += ["Smoke (secret-safe: secrets via `${VAR}` expansion, never printed):", ""]
        for family, f in sorted(facts_cred.items()):
            env_vars = f.get("env_vars", [])
            if not env_vars:
                continue
            endpoint = f.get("endpoint", "")
            block = [f"# {family}" + (f" — endpoint (metadata): {endpoint}" if endpoint else "")]
            for v in env_vars:
                if "BASE_URL" in v or v.endswith("_URL"):
                    block.append(f'export {v}="{endpoint or "<endpoint>"}"')
                else:
                    block.append(f'export {v}="<value supplied at runtime; never printed>"')
            ae = " ".join(f"--ae '{v}=${{{v}}}'" for v in env_vars)
            block.append(f"harbor run -c <job-config>.json --yes {ae}")
            out += [f"### {family}", ""]
            out += code_block("\n".join(block))
            out += [""]
    else:
        out += ["_Smoke command shapes require the operator facts file (see above)._", ""]

    # ---- evidence status ----
    out += ["## Evidence status", ""]
    if evidence:
        out += md_table(
            ["Agent", "Auth mode", "Model", "Status", "Note"],
            [[e.get("agent", ""), e.get("auth_mode", ""), e.get("model", ""), e.get("status", ""), e.get("note", "")]
             for e in evidence],
        )
        out += [""]
    else:
        out += [
            "_TODO(operator): record smoke-evidence status in the facts file. Live",
            "trial receipts stay out of the repository unless intentionally redacted._",
            "",
        ]
    out += [
        "Status vocabulary: `smoke-verified` (task reward 1.0),",
        "`provider-reached-not-satisfied` (provider calls succeeded, task not met),",
        "`not-yet-verified`.",
        "",
    ]

    # ---- regeneration ----
    out += ["## Regeneration & maintenance", ""]
    if facts_notes:
        out += [facts_notes, ""]
    out += [
        "Re-run the one-shot command at the top of this file after host, tool, or",
        "provider changes. Non-probeable facts live in",
        "`.agents/knowledge/development-machine-facts.md`; keep it secret-free and",
        "date-stamped.",
        "",
    ]

    return "\n".join(out)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--probe-json", type=Path, default=None, help="read probe JSON from a file instead of stdin")
    parser.add_argument("--facts", type=Path, default=Path(".agents/knowledge/development-machine-facts.md"))
    parser.add_argument("--output", type=Path, default=Path(".agents/local/DevelopmentMachine.md"))
    args = parser.parse_args()

    if args.probe_json:
        probe_text = args.probe_json.read_text(encoding="utf-8")
    else:
        probe_text = sys.stdin.read()
    probe = load_json(probe_text, args.probe_json.name if args.probe_json else "stdin")
    guard(probe, "probe JSON")

    facts = load_facts(str(args.facts))
    guard(facts, f"facts file {args.facts}")

    doc = render(probe, facts)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(doc, encoding="utf-8")
    print(f"Wrote {args.output}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
